<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNLOrBmn\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNLOrBmn/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNLOrBmn.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNLOrBmn\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNLOrBmn\App_KernelDevDebugContainer([
    'container.build_hash' => 'NLOrBmn',
    'container.build_id' => '2e5b6053',
    'container.build_time' => 1592481545,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNLOrBmn');
